InventoryManagement.Dreamer.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagement.Dreamer.Web.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        //
        // GET: /Dashboard/

        public ActionResult Home()
        {
            return View();
        }

    }
}

InventoryManagement.Dreamer.Web/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InventoryManagement.Dreamer.Domain.Interfaces;
using InventoryManagement.Dreamer.Domain.Metadata;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

namespace InventoryManagement.Dreamer.Web.Controllers
{
    [Authorize]
    public class HistoryController : Controller
    {
        private readonly IBasicUnit _basicUnit;

        public HistoryController(IBasicUnit basicUnit)
        {
            _basicUnit = basicUnit;
        }

        public ActionResult Purchase()
        {
            var searchMetadata = new TranctionSearchMetadata { IsSales = false };
            return View("TransctionHistory",searchMetadata);
        }

        public ActionResult Sales()
        {
            var searchMetadata = new TranctionSearchMetadata { IsSales = true };
            return View("TransctionHistory", searchMetadata);
        }

        public ActionResult GetTransctions(TranctionSearchMetadata tranctionSearchMetadata, [DataSourceRequest] DataSourceRequest request)
        {
            return Json(_basicUnit.Transactions.GetTransctions(x => tranctionSearchMetadata.From <= x.TransactionDate
                                                               && tranctionSearchMetadata.To >= x.TransactionDate
                                                               && x.IsSales == tranctionSearchMetadata.IsSales)
                                  .ToDataSourceResult(request));
        }

        public ActionResult GetTransctionHistory(Guid transctionId, [DataSourceRequest] DataSourceRequest request)
        {

            return Json(_basicUnit.TransactionHistorys.GetTransctionHistorys(x=>!x.IsDeleted && x.TransctionId == transctionId)
                                  .ToDataSourceResult(request));
        }
    }
}

InventoryManagement.Dreamer.Web/Views/Dashboard/Home.cshtml
@Styles.Render("~/Content/Dashboard")
@{
    ViewBag.Title = "Home";
}

<div id="DashboardContiner">
    <div class="keepUpAndDown">
        <div id="Product" class="KeepSideBySide" data-metrotile="true" data-first-image="/Content/Images/Product.png" data-first-text="Product">
        </div>

        <div id="Stock" class="KeepSideBySide" data-metrotile="true" data-first-image="/Content/Images/Stock.png" data-first-text="Stock">
        </div>

        <div id="PurchaseHistory" class="KeepSideBySide" data-metrotile="true" data-first-image="/Content/Images/PurchaseHistory.png" data-first-text="Purchase History">
        </div>
        <div id="CreateAccount" class="KeepSideBySide" data-metrotile="true" data-first-image="/Content/Images/UserAdd.png" data-first-text="Create User Account">
        </div>

    </div>
    <br />
    <div class="keepUpAndDown">
        <div id="Purchase" class="KeepSideBySide" data-metrotile="true" data-first-image="/Content/Images/Purchase.png" data-first-text="Purchase">
        </div>

        <div id="Sales" class="KeepSideBySide" data-metrotile="true" data-first-image="/Content/Images/Sales.png" data-first-text="Sales">
        </div>

        <div id="SalesHistory" class="KeepSideBySide" data-metrotile="true" data-first-image="/Content/Images/SalesHistory.png" data-first-text="Sales History">
        </div>
        <div id="ChangePassword" class="KeepSideBySide" data-metrotile="true" data-first-image="/Content/Images/CahngePassword.png" data-first-text="Change Password">
        </div>
    </div>
</div>
@section scripts
{
    @Scripts.Render("~/bundles/jquery")
}

<script type="text/javascript">

    $("#Product").click(function () {
        document.location.href = "@Url.Action("Product","Product")";
    });

    $("#Stock").click(function () {
        document.location.href = "@Url.Action("Stock","Stock")";;
    });

    $("#Purchase").click(function () {
        document.location.href = "@Url.Action("Purchase","Transaction")";
    });

    $("#Sales").click(function () {
        document.location.href = "@Url.Action("Sales","Transaction")";;
    });

    $("#PurchaseHistory").click(function () {
        document.location.href = "@Url.Action("Purchase","History")";;
    });

    $("#SalesHistory").click(function () {
        document.location.href = "@Url.Action("Sales","History")";;
    });

    $("#ChangePassword").click(function () {
        document.location.href = "@Url.Action("Manage","Account")";;
    });

</script>